pulsar-edit/ppm

src/apm.coffee
With the `Atom.io` API becoming more and more unstable, taking a long time to return, failing to return, or just straight up failing to resolve.
So this PR adds our 'beta' Backend. 
This is the backend that I've been working on since the announcement of the sunset, and while currently unfinished, would allow users to search, query, and install all packages that were originally on the Atom.io Package Repository.
While this PR is simple the implications are large. Feel free to discuss the change.
Additionally since PPM is a submodule in `Pulsar` that means as soon as this is committed, any additional builds of Pulsar should automatically get this update.
=> Added Our Backend

spec/publish-spec.coffee, src/apm.coffee, src/develop.coffee, src/install.coffee, src/links.coffee, src/publish.coffee, src/rebuild-module-cache.coffee, src/star.coffee, src/uninstall.coffee, src/unlink.coffee, src/upgrade.coffee, src/view.coffee
Basically, re-adjusting things here that are still pointing to "atom home" to start searching on "pulsar home"
=> Pulsar adjustments

src/apm.coffee
This fixes the issue with core packages not showing in settings view caused by the change of `apm` install folder to `ppm` in pulsar-edit/pulsar#125.
=> Use ppm as basename in getResourcePath checks

src/featured.coffee
This fixes #37 and pulsar-edit/pulsar#137 by not checking for `latest` key in `releases`. If the issue pulsar-edit/package-backend#3 is fixed, then this PR can be rejected.
=> Fix empty featured packages

src/apm-cli.coffee
Instead of displaying:
```
Usage: apm <something>
```
Now it displays:
```
Usage: pulsar --package <something>
```
=> Better help command display

src/apm.coffee
The old atom.io Electron headers URL is going down, per the updated sunset announcement.
Likewise, the old gh-contractor-zcbenz Amazon AWS/S3 bucket is no-longer guaranteed to be active, and may go away at any time.
(See: https://github.blog/2022-06-08-sunsetting-atom/#if-im-using-atom-what-changes-can-i-expect-after-the-sunset and https://www.electronjs.org/blog/s3-bucket-change)
So, this commit updates our package manager to get the Electron headers from the new 'artifacts.electronjs.org/headers/dist' location.
This is the correct, official place to get the Electron headers, according to the blog post above at electronjs.org.
Ensures we can continue to build native C/C++ code for certain Atom/Pulsar packages that use it.
(For example: several of the language packages have C/C++ addon …
=> src: Update Electron header download URL

src/publish.coffee
This is a REQUIREMENT for package publishing on the Pulsar backend.
The original Atom documentation had a section "parameters" where they did not clarify whether they were using form parameters, or query parameters. Due to the language we assumed that it was query parameters.
See here in the Discord for context: https://discord.com/channels/992103415163396136/992110095641088001/
The submodule within Pulsar will need to be updated to point to the new hash once this has been merged
=> Convert body params to query params

CONTRIBUTING.md, README.md, src/apm-cli.coffee, src/apm.coffee, src/auth.coffee, src/featured.coffee, src/install.coffee, src/link.coffee, src/login.coffee, src/publish.coffee, src/search.coffee, src/stars.coffee
Mostly this just fixes a few links:
- Org .github CONTRIBUTING.md link
- Update of `.com` to `.dev` links
However I also did a quick rebrand of the readme at the same time and I'm not sure if this is technically correct or not.
Elsewhere in the documentation we almost exclusively use `pulsar -p` as the "new" alias of `apm`.
However here it makes sense to keep the "direct" style of command in my mind. However this is where there is an issue because the binary itself is still `apm`.
So what I've done is change all `apm` instances to `ppm` in the style of https://github.com/pulsar-edit/pulsar/pull/273 this PR that is meant to add `ppm` to the PATH.
However this is also still correct if we used `apm` if we were talking about executing the binary directly so I don't know what the correct …
=> Fix .com links, pulsar rebranding and rebranding readme

.gitattributes
Prevents large, line-ending-only diffs when package metadata (mostly the dependencies) are updated on various OSes/platforms.
Especially Windows (CRLF) vs macOS/Linux (LF).
<details><summary>Why do this PR? (click to expand):</summary>
_(This was a rare but very annoying issue that cropped up _very infrequently_ over at upstream (official Atom team) apm and at atom-community/apm repos.)_
_(It hasn't been a problem here so far, and maybe it was only an issue once upon a time, given that **I think** the `package-lock.json` was actually committed with **mixed line endings** within the one file at one point, if you can believe that???!?! So I don't expect it to happen here again, and yet having to commit a "normalize line endings" commit of the file itself is so annoying if it were to happen …
=> meta: Normalize package.json and lockfile line endings

src/apm.coffee
Changes:
Updates the default install paths for each OS, based on where our new bundled packages (made by electron-builder) install to.
Relatedly, adjust logic which finds the app on macOS, for the rebrand.
---
Notes:
- A relative path from ppm's install dir in the bundled package is tried first, and then the default absolute install path of the whole app is hard-coded as a fallback. The relative path should work for any fully bundled/packaged copy of Pulsar.
- **This hard-coded fallback shouldn't be needed in actual installs of Pulsar -- this commit is mostly useful for situations where ppm is not bundled with the editor, such as when developing or testing ppm in the context of its own git repo.**
- on macOS, ppm also uses a search-on-disk "mdfind" command to find other potential install …
=> src: Update default Pulsar install paths

bin/npm.cmd, script/postinstall.cmd
(Without breaking `npm install` for this repo, either.)
This PR fixes the scenario where you want to install this repo's dependencies with Yarn on Windows. (Should allow `yarn build:apm` to actually work on Windows over at the Pulsar core repo!) It does so by working around some differences with how _Yarn_ interacts with Windows' cmd.exe command line interpreter and batch scripts, compared to how _npm_ interacts with cmd.exe and batch scripts.
For technical explanation of each change, see the commit messages. Each change is no more than one line (and no more than 6 characters, at that!), other than whitespace. So do consider looking at the diff first, then referring to the commit messages if/only if you have further questions. 100% of the changes are found in two .cmd batch script files. …
=> Fix installing with yarn on Windows

src/upgrade.coffee
This is a fun one. Remember #56? I thought it made it possible to update packages installed via GitHub when the package's default branch is `main` instead of `master`. Instead, I introduced a dumb mistake, the result of which was that no GitHub-installed packages _ever_ realized that their upstream had changed.
The diff makes it clear what I did wrong.
Because the relevant specs are written wrong — probably because it was too hard to write them correctly.
To find out if there's a new version of a package, `ppm` compares the SHA of the version it has with the SHA on the tip of the head remote branch, then upgrades the package (or shows it in a list) if the two don't match. The way the spec works is to artificially change _the SHA of the version it has_, rather than simulate retrieving the …
=> Fix inability to notice newer versions of git-installed packages

yarn.lock
This should make yarn.lock stable across multiple installs.
(Not sure why this diff wasn't part of the npm bump, but who knows?)
=> meta: Actually sync yarn.lock

src/auth.coffee, src/ci.coffee, src/clean.coffee, src/config.coffee, src/dedupe.coffee, src/develop.coffee, src/disable.coffee, src/docs.coffee, src/enable.coffee, src/featured.coffee, src/init.coffee, src/install.coffee, src/link.coffee, src/links.coffee, src/list.coffee, src/login.coffee, src/publish.coffee, src/rebuild-module-cache.coffee, src/rebuild.coffee, src/search.coffee, src/star.coffee, src/stars.coffee, src/test.coffee, src/uninstall.coffee, src/unlink.coffee, src/unpublish.coffee, src/unstar.coffee, src/upgrade.coffee, src/view.coffee
Replace all "apm" occurrences by "ppm" in console help messages.
=> Replace "apm" by "ppm" in help messages.

bin/ppm, bin/ppm.cmd, script/postinstall.js
**I think the PR title pretty much says what's going on here, but my extended thoughts below for anyone curious**
Makes it easier to integrate ppm in various contexts, such as on the user's PATH to be run from the CLI, without having to run it as 'apm'.
**Notably, this should make it easier to get a `ppm.cmd` command on users' PATHs on Windows, based on the method we've been using so far, which ends up giving users an `apm.cmd` command on Windows...**
_Aside/commentary: It also subjectively lets us do something less "jank" feeling than for `ppm` to be a symlink to `apm` on Unix-likes (Linux + macOS)... We can do `ppm` --> `ppm` instead now... But that hasn't been an issue thus far, honestly. I don't worry myself over that one, truthfully. It's just been an itch at the back of my neck to …
=> Add 'ppm' bins to complement existing 'apm' bins

.github/workflows/CI.yml, package-lock.json, package.json, src/command.coffee, yarn.lock
Move to our fork of npm, which changes nothing other than depending on newer node-gyp. For ppm, this effectively bumps node-gyp from 5.1.1 to ^9.4.0.
This adds support for newer OSes/compiler toolchains/etc. (And _drops_ support for Python 2.x, and Python 3.6 or older.)
See the node-gyp changelog for more info:
https://github.com/nodejs/node-gyp/blob/main/CHANGELOG.md
This node-gyp upgrade has been a wishlist item for the development team (and others?) for quite a while now.
=> Switch to our npm fork, to get newer node-gyp (node-gyp 9.x)

script/bundled-node-version.js, script/postinstall.js
Before this change, if a Windows user plans to contribute and saves PPM into a directory that has spaces in it's path, the scripts will fail. Wrapping all paths to files with `"` ensures it's handled as a string by the terminal, ensuring Windows users can contribute, without having to save this into a specific directory
=> Make `postinstall` scripts work on Windows with spaces in cwd path

src/unpublish.js
Conversation thread here: https://discord.com/channels/992103415163396136/1147891572533362779/1147891572533362779
We decided it would be best to clarify the wording as it isn't clear from the text in ppm that the unpublish command will make the package name permanently unavailable.
This just adds a line to clarify that.
=> Update unpublishing wording

spec/upgrade-spec.js, src/upgrade.js
This PR allows PPM to skip checking for updates for bundled packages within Pulsar.
This only works if the package is not a valid git repository, which is true for the vast majority of our bundled packages.
Although, some outliers to this exist, those can be determined by checking the remaining items [here](https://github.com/pulsar-edit/pulsar/issues/512). As for all other of the 81 bundled packages, this should allow them to be silently skipped. Assumed to always be up to date by PPM.
This is done by checking the `repository` of the `package.json` of the package and determining if it's the same as the repository of Pulsar itself.
=> Skip update checks for bundled packages

package-lock.json, package.json, yarn.lock
There is an issue with code-signing apps built with node-gyp 9.1.0 or newer. (This is due to unforeseen consequences of a change I authored in node-gyp, unfortunately. The change in question: https://github.com/nodejs/node-gyp/commit/b9ddcd5bbd93b05b03674836b6ebdae2c2e74c8c.)
So, this PR bumps node-gyp to the latest commit from node-gyp repo's `main` branch, currently https://github.com/nodejs/node-gyp/commit/d3615c66f7e7a65de48ce9860b1fe13710d20988.
This includes a fix for better compatibility with app signing on macOS (https://github.com/nodejs/node-gyp/commit/0f1f667b737d21905e283df100a2cb639993562a).
Said commit with the fix isn't a part of any tagged or published-to-npm-package-registry releases yet, so we have to grab it from the node-gyp repo, rather than, say, as a version from …
=> Update npm and node-gyp, for macOS signing fix

src/develop.js, src/featured.js, src/install.js, src/publish.js, src/request.js, src/search.js, src/star.js, src/stars.js, src/unstar.js
It was brought to my attention on [Discord](https://discord.com/channels/992103415163396136/992110062992621598/1155591813785194626) that a61aa7e121bc93723f675198778b6006fdd66738 broke error handling in PPM.
The clue to find out what had gone wrong was the fact that the unstar command still worked.
This is because in that PR I had told `superagent` a list of status codes to not error on. This means that when we got, say a 404, the actual `error` object returned to the callback would be `null` even though those commands then relied on the `error` object to determine what had gone wrong. 
So what I've done, is provide both the `error` and `body` to the `request.getErrorMessage()` so that we can check for errors in either of them. 
Meaning when a request fails we will:
1. Look first for …
=> Fix Error Handling

package-lock.json, yarn.lock
Bump nan from 2.16.0 to 2.18.0. (Tiny, tiny, single-dependency bump in yarn.lock and package-lock.json only!)
(I recommend reviewers to check the diff to see that this is a super tiny PR.)
nan is a slightly more stable API target for compiling C/C++ addons for NodeJS projects against, attempting to hide the complexity and moving target that is the V8 engine internals beneath a more manageable, and once again a more "stable" API target.
For more info, see: https://github.com/nodejs/nan
We occasionally need to bump this package for compatibility with newer NodeJS versions that bundle newer versions of V8, or carry different V8 patches, etc. Newer nan versions get put out from time to time to address breakages in nan's "stable" API when used against the newer/different copies of V8 found in …
=> deps: Bump nan for compatibility with newer NodeJS

.github/workflows/CI.yml
Install a global copy of node-gyp for Yarn to use. Works around a really weird bug.
Details of the bug (and explanation of the workaround) below:
---
Yarn install in Yarn v1.x has a really obscure bug that only happens for certain repos that "require node-gyp", and even then, only if the globally installed copy of npm is v9.7.2 or newer (or if there is no global copy of npm installed, which is quite rare.)
In these unusual (and complex to describe) circumstances, this repo's postinstall script will not run, due to the bug in Yarn v1.x.
Unfortunately for us, the versions of npm Yarn v1.x is incompatible with in this manner, npm v9.7.2 or newer, are bundled with NodeJS v18.18.0 and newer, as well as NodeJS v20.4.0 and newer. So, this is the new normal.
Working around this is easy IRL. Yarn …
=> CI: Work around a weird bug in Yarn v1.x

src/uninstall.js
So, we stopped *using* these pings on our implementation of the backend, since it doesn't really make sense to decrement the install count when someone uninstalls... arguably. And it may or may not have simply been telemetry when the O.G. Atom backend was expecting this to be an authed action.
Since we don't need to auth or ping the backend for uninstalls... Just delete the code that does it!
=> src: Stop pinging backend during package uninstalls

.github/workflows/CI.yml
This PR aims to resolve the CI issues we are seeing on this repo.
As activity has been spares over here, seems this repo had never yet received the new `setuptools` and Python 3.12+ actions logic.
So this PR simply takes what's mostly used over at Pulsar, and adds it's logic to the CI here.
=> Fix Newer NodeJS CI

src/install.js
These flags do not *actually* take commit SHAs as arguments, only branch or tag names.
The flags are aliases of one-another and work the exact same -- *either* flag can take a branch name *or* tag name. No SHAs.
---
Optional context: Issue report https://github.com/pulsar-edit/pulsar/issues/821 over at the core repo brought this back to my attention, although I believe it had been brought up somewhere in Discord a long time ago, just now getting around to finally updating the usage/help text to be accurate.
=> src: Fix usage/help text (and error message) for -b/-t flags for ppm install

src/uninstall.js
This is a quick follow-up to some code removal in PR 103.
In #103, after removing some code that does a ping to the backend (which we no-op/ignore anyway, on the backend side...) I didn't notice `packageVersion` is now defined but unused with those code removals.
Basically this is one line I missed in the cleanup. Things that were part of making the backend ping work. With that removed, this line/variable serve no purpose.
This basically finishes the cleanup started in #103.
**(TL;DR: Another too-long writeup of a tiny diff. This is a one-liner removing a defined but unused var.)**
EDIT: Whoops, mentioned and tagged the wrong PR. This PR follows-up on PR 103, not PR 95...
=> src: Delete unused code in uninstall.js

src/clean.js, src/docs.js, src/git.js, src/login.js, src/uninstall.js
This PR removes most of the unused variables within the codebase. Advised via the Codacy recommendations.
This also has a focus on imports mostly, and ignored any unused variables that begin with `_` for the time being.
But for this PR while touching unrelated files, I hope keeping the purpose identical between all of them, it's not too hard to review.
=> Remove unused Variables

.eslintrc.js, script/download-node.js, spec/enable-spec.js, spec/upgrade-spec.js, src/clean.js, src/fs.js
Alright, apologies to @DeeDeeG for the fact I just don't seem to stop making PPM PRs lol.
This PR should be the last one of the ones I've had semi ready to go, and implements the majority of the low hanging fruit flagged on codacy.
Thanks again to anyone able to review this one, and hopefully I'll calm down in this repo afterwards
=> Implement Codacy Recommendations

spec/publish-spec.js, src/apm.js, src/publish.js
These are just the ones I found when trying to run `ppm publish patch`, but I'm sure there are other bugs. The PPM rewrite was gigantic.
=> Fix bugs found in `publish` after 1.112 release

src/publish.js
The command was hanging because `setTimeout` was being called over and over, rather than just as needed (because the tag wasn't available yet). The `setTimeout` started out in one wrong place and then I “fixed” it by moving the `setTimeout` to a _different_ wrong place.
There is a separate issue here: the API calls to GitHub could fail for any number of reasons. One reason they failed for me was because I exceeded the unauthenticated rate limit! This command should at least handle the error cases, but I believe it can also use the very auth token we use for the package backend in order to enable a much higher rate limit. Both of those are worth doing, but I'll save them for a different PR.
=> Fix placement of `setTimeout`

spec/test-spec.js, src/test.js
If pulsar is installed from the .deb package,
the command `ppm test` fails with this error:
`Error spawning atom: spawn atom ENOENT`
Using `pulsar` instead of `atom` fixes this.
=> Fix test failure due to missing atom command

templates/theme/styles/syntax-variables.less
Suppose you've written a package that makes some sort of editor enhancement. For various reasons, you'd _really_ like to know what color is used to highlight variables in their syntax theme.
The good news is that Pulsar defines a list of variables in `syntax-variables.less` in each of the eight built-in themes which lists this token and others. (Amazingly, not all of them _actually consume_ these variables in the rest of the stylesheets, so it may only be coincidental when the values line up; but B+ for effort.) Pulsar also [defines some fallback values](https://github.com/pulsar-edit/pulsar/commit/91710894660018988cfa87c5132333129dd1f0c6) so that these values can at least be used consistently in a user's stylesheet file, and in any package stylesheet, without Less complaining about an …
=> Update syntax-variables.less to include language entity colors

spec/link-spec.js, src/link.js
Hi there, now that I'm using Pulsar, I find myself with a fair number of old Atom packages that need tweaks or updates, and so I'm doing this dance a lot:
```
$ git clone $PACKAGE_THAT_NEEDS_A_FIX_OR_UPDATE
$ cd $PACKAGE_THAT_NEEDS_A_FIX_OR_UPDATE
$ npm i
$ ppm link
Linking $CURRENTLY_INSTALLED_PACKAGE to $PACKAGE_THAT_NEEDS_A_FIX_OR_UPDATE failed: EEXIST: file already exists, symlink '$PACKAGE_THAT_NEEDS_A_FIX_OR_UPDATE' -> '$CURRENTLY_INSTALLED_PACKAGE'
```
Obviously, the fix is simple and easy (`rm -rf $CURRENTLY_INSTALLED_PACKAGE` & try again), but it also felt like a `--force` flag would be handy to just do that for me while rerunning the command.
This was a pretty trivial change, and I'm happy to make changes as desired. I added 2 tests: one to confirm that it errors if the target …
=> feat(link): add --force flag

spec/publish-spec.js, src/publish.js
After numerous issues and reports and pain points of this publish logic, we hit a point after enabling strict versioning on the backend to discover that the original logic completely fails now.
I'll try to update this with more details with more time, but for now, here's an attempt that should resolve our woes.
=> Rewrite publish logic

.github/workflows/CI.yml
This reverts commit 12c276b6233cba8ec60bccfe58bc33c618e0de60.
Revert a now-unnecessary workaround.
Amazingly, this issue has been avoided in the latest npm versions, as npm have restored the files Yarn 1.x rather over-optimistically required npm to have.
NodeJS has in turn bundled these versions of npm with the fixes before the final minor/patch release of every major version of NodeJS.
This is effectively a solved issue if you use the latest patch versions of NodeJS. No more incompatibility with Yarn 1.x in these narrow cases.
(Admittedly, the Yarn 1.x issue was due to a genuine bug in Yarn 1.x, not a deliberate thing from the Yarn authors I don't think).
---
See this comment for all the (somewhat exhaustive!) research I did to support making this change: …
=> Revert "CI: Work around a weird bug in Yarn v1.x"

package.json, src/package-converter.js, src/text-mate-theme.js, yarn.lock
These were some low-hanging fruit for upgradable dependencies.
(And some slightly higher-hanging fruit, TBH, see the custom resolutions in `package.json`) 
Might as well, if we can, right?
Tests pass on my machine, and I can still install packages. (I tried `language-carp` and `atom-ide-base`; Both had no obvious issues installing, in terms of being able to run `ppm install language-carp` or `ppm install atom-ide-base` without running into any errors on the CLI, at least.)
Additional manual testing may be desirable, if we can get folks with the knowledge and time to thoroughly do so. Otherwise, we may just have to ask people to test it in the wild if we want to update these deps. In which case, best to have it in Rolling for a while and put out a call for testing there. Otherwise, we can …
=> Update many dependencies

.eslintrc.js, spec/publish-spec.js, src/publish.js
Suppose a user maintains a package called `old-name` and wants to rename it to `new-name`. When the user runs
```shell
ppm publish patch --rename new-name
```
`ppm` does these things (and other things, but these are the ones relevant to this discussion):
* automatically updates the `name` field in `package.json` to the new value (in fact, it will scold you if you try to do this manually); then
* asks the API whether the package already exists.
* if so, it POSTs to `/api/packages/old-name/versions/` with the `package.json` metadata;
* if not, it POSTs to `/api/packages/` with that same metadata (since this is a brand-new publish of a package).
If, in this scenario, the API got confused and told us that the package _didn't_ exist, we'd end up treating this rename task as the publishing of a …
=> Fix incorrect behavior on package rename

src/ci.js, src/dedupe.js, src/develop.js, src/install.js
Within this repo we use the `async` package nearly everywhere, which while it may have been a game changer when using CoffeeScript, I'd argue with current versions of JavaScript, this isn't really needed.
Although replacing it's usage isn't always straightforward.
So what I've done here is remove the straightforward sections, which mostly consists of [`async.waterfall()`](https://caolan.github.io/async/v3/docs.html#waterfall) which simply would run an array of async functions one after the other.
Due to this simplicity I was able to easily convert any instances of `async.waterfall()` to a few `await` calls wrapped in a `try...catch` block.
But I've otherwise left `async` usage in locations with more complex setups, that wouldn't be a simple translation to do. But eventually I'd hope to …
=> Begin less reliance on `async` package: Await as we go

src/apm.js
Fixes #126.
We've known for a while about an issue where `ppm rebuild` fails to work properly on Apple Silicon. That command is run whenever a native module needs to be recompiled — either for a new processor architecture or for a new version of Electron — and there's even a GUI for it.
This is what it might look like for an end user, as it did for me last week when I got a new M3 MacBook Pro:
https://github.com/user-attachments/assets/77b27b32-2937-4b61-a82e-bba419c08993
The built-in `update-package-dependencies` package is a frontend to `ppm rebuild`. Notice how it doesn't say “failed to rebuild the package”; it thinks it's succeeded, and yet after a window reload it once again flags the native module as being for the wrong architecture.
This was on my radar because some of …
=> Remove hard-coded architecture on Mac

src/apm-cli.js, src/ci.js, src/command.js, src/config.js, src/dedupe.js, src/develop.js, src/disable.js, src/enable.js, src/featured.js, src/install.js, src/list.js, src/package-converter.js, src/publish.js, src/rebuild.js, src/request.js, src/search.js, src/star.js, src/stars.js, src/text-mate-theme.js, src/theme-converter.js, src/tree.js, src/unpublish.js, src/unstar.js, src/upgrade.js, src/view.js
Now, only the overly custom part of underscore-plus remains: this config reading and writing that should rather get a separate module/package.
The implementations themselves could be further improved as better Set operations land, mostly in Node v22.
=> Eliminate trivial underscore

.github/workflows/CI.yml, package.json, yarn.lock
Includes an edition of [`nodejs/gyp-next`](https://github.com/nodejs/gyp-next) which vendors Python [`packaging`](https://pypi.org/project/packaging/) library and moves away from `distutils`, which used to be shipped with Python, but [was deprecated starting in Python 3.10, and then dropped starting in Python 3.12](https://peps.python.org/pep-0632/).
---
This solves an error -- Python 3.12 users without `distutils` (or else [`setuptools`](https://pypi.org/project/setuptools/) which provides `distutils`) on their systems would get an error like the following when trying to build native C/C++ code:
```
from distutils.version import StrictVersion
ModuleNotFoundError: No module named 'distutils'
```
[Newer gyp-next 0.16.0+](https://github.com/nodejs/gyp-next/compare/v0.15.1...v0.16.0) (and by …
=> deps: Bump node-gyp to latest ^10.2.0 for Python 3.12 compat

package.json, script/download-node.js
It was only used in the download-node script - now that also uses superagent instead.
I tested the download locally and it did succeed.
=> Remove dependency on "request" package

package.json, src/login.js, src/upgrade.js, yarn.lock
Read v4 declares a dependency on Node v18 at least and the bundled Node version is v16.0.0 still. The modifications aren't big but that upgrade would be the way even further. Other than that, this package didn't change a lot. It's supposed to "just work" if one exports the `read` function appropriately (not as a "default" import), with an async interface that we pretty much already had because of the promptX kind of methods.
=> Update to read v3
